### ISSUE TITLE
Şifre değişikliği ve mail gönderimi

### ISSUE THREAD

**Issue by RudyardKipling** [instela/instela-issues#911]
Merhaba,

Şifremi unuttum kısmından, mail adresini girip yeni şifre talep ettiğimde hata ekranıyla karşılaşıyorum. Bunu şifremi biliyor iken denedim. Yeni şifre talep ettim ve aşağıdaki görüntüdeki hatayı aldım. Şifrem değişmiş fakat, değişen şifremin ne olduğunu bilmiyorum. Normal şifremle şu an giriş yapamıyorum anlayacağınız. Teşekkürler.
http://i.hizliresim.com/A3BGb7.png

**Comment by cagataygurturk** [comment]
Sorun duzeldi tekrar sifre isteyebilirsin

**Comment by RudyardKipling** [comment]
Şu an çalışıyor, teşekkürler.
